# Generated by Django 4.2.17 on 2025-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cloths",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("size", models.CharField(max_length=10)),
                ("price", models.CharField(max_length=10000)),
                ("stock", models.CharField(max_length=100)),
            ],
        ),
    ]
